### ISSUE TITLE
deploy-spinnaker fails

### ISSUE THREAD

**Issue by eamonnfaherty** [aws-samples/aws-deploy-spinnaker-halyard#10]
I have run:

```
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
aws cloudformation create-stack --stack-name codebuild-projects \
    --template-body "$(cat resources/cloudformation/codebuild-projects.yaml)" \
    --parameters ParameterKey=CodeBuildArtifactsBucketName,ParameterValue=codebuild-artifacts-${ACCOUNT_ID} \
                 ParameterKey=SourceLocation,ParameterValue=https://github.com/eamonnfaherty/aws-deploy-spinnaker-halyard \
                 ParameterKey=SourceType,ParameterValue=GITHUB \
    --capabilities CAPABILITY_NAMED_IAM
```

Then I ran the create-eks project.

Following that I ran the deploy-spinnaker project passing in the new sg I created.

During that project I get the following error:

[Container] 2019/01/29 22:01:36 Running command aws s3 cp s3://codebuild-artifacts-${ACCOUNT_ID}/create-eks/files/resources/kubernetes/kubeconfig-no-role.yaml /home/spinnaker/.kube/config
fatal error: An error occurred (404) when calling the HeadObject operation: Key "create-eks/files/resources/kubernetes/kubeconfig-no-role.yaml" does not exist
 [Container] 2019/01/29 22:01:37 Command did not exit successfully aws s3 cp s3://codebuild-artifacts-${ACCOUNT_ID}/create-eks/files/resources/kubernetes/kubeconfig-no-role.yaml /home/spinnaker/.kube/config exit status 1

It turns out the bucket s3://codebuild-artifacts-${ACCOUNT_ID} has been created but is empty.

**Comment by edwinavalos** [comment]
@eamonnfaherty if you can, can you check if the Create EKS project had a problem with archiving the kubeconfigs?

The upload is controlled via this section:
https://github.com/aws-samples/aws-deploy-spinnaker-halyard/blob/master/buildspec-infra.yaml#L17-L20

**Comment by eamonnfaherty** [comment]
That does seem to be failing:

```
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Expanding artifact file paths for base directory .$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Assembling file list$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Expanding resources/kubernetes/kubeconfig.yaml$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Skipping invalid artifact path resources/kubernetes/kubeconfig.yaml$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Expanding resources/kubernetes/kubeconfig-no-role.yaml$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Skipping invalid artifact path resources/kubernetes/kubeconfig-no-role.yaml$
^I1548799177958$
EVENTS^I1548799177981^I[Container] 2019/01/29 21:59:35 Phase complete: UPLOAD_ARTIFACTS Success: false$
```

I have dug through the logs and I think this is where the error is occurring:

```
EVENTS	1548799177981	[Container] 2019/01/29 21:59:35 Command did not exit successfully ./scripts/create_eks_cluster.sh -k ${K8S_NAME} -s ${K8S_KEYPAIR} -b ${BUCKET_NAME} exit status 255
	1548799177958
EVENTS	1548799177981	[Container] 2019/01/29 21:59:35 Phase complete: BUILD Success: false
	1548799177958
EVENTS	1548799177981	[Container] 2019/01/29 21:59:35 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./scripts/create_eks_cluster.sh -k ${K8S_NAME} -s ${K8S_KEYPAIR} -b ${BUCKET_NAME}. Reason: exit status 255
	1548799177958
EVENTS	1548799177981	[Container] 2019/01/29 21:59:35 Entering phase POST_BUILD

```

Please let me know if you would like a dump of the full logs.

**Comment by eamonnfaherty** [comment]
I checked into it as I had more time and it looks like I did not create the ssh key the second time around.  

I created the key, reran the solution and this build step passed.

Sorry for the false negative!
