### ISSUE TITLE
could not get token: AccessDenied: Access denied

### ISSUE THREAD

**Issue by Tiny-wlx** [aws-samples/aws-deploy-spinnaker-halyard#2]
Hi,
After done followed with "Accessing EKS" section,it show

could not get token: AccessDenied: Access denied
	status code: 403, request id: 171e9092-dcf4-11e8-a469-b5710cea842f
could not get token: AccessDenied: Access denied
	status code: 403, request id: 17ff05e9-dcf4-11e8-81f7-81f4a4485f32
could not get token: AccessDenied: Access denied
	status code: 403, request id: 18f265e0-dcf4-11e8-9fb9-81dddd5c32d7
could not get token: AccessDenied: Access denied
	status code: 403, request id: 19e1335a-dcf4-11e8-8932-897b76b26a86
could not get token: AccessDenied: Access denied
	status code: 403, request id: 1ac3f20a-dcf4-11e8-9297-1d74c794ecf4

what can i do to fix this?

Thanks

**Comment by edwinavalos** [comment]
Hello @Tiny-wlx ,

That error might be related to not adding whatever identity you are running kubectl commands as not being added to the EKS-Admin role.

During the standing up of the EKS cluster there is a role created that follows the naming scheme:
arn:aws:iam::<account_number>:role/EKSAdminRole, that role needs to have your user or role added to it.

If you are using user credentials, you can go into the IAM roles Trust Relationships in the IAM console click "Edit" and make the relationship look like

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com",
        "AWS": "arn:aws:iam::<account_number>:user/my-eks-admin-user"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Where if I am calling kubectl with the kubeconfig configured to assume the EKS Admin role, my credentials tied to my-eks-admin-user will be able to obtain the kubernetes access token.

Let me know if you need anymore help!

-Edwin

**Comment by Tiny-wlx** [comment]
Hi Edwin，

Thanks for you reply.

I access EKS on my macos, May be i should use an ec2 instance with same vpc, i will check later.

Thanks for your help!

-Tiny

**Comment by Tiny-wlx** [comment]
Hi Edwin,

it's work currently.

Thank you very much!

-Tiny

**Comment by Connectio-IT** [comment]
PS C:\Program Files\Kubernetes> kubectl get service
error: You must be logged in to the server (Unauthorized)

**Comment by GMKBabu777** [comment]
PS C:\Program Files\Kubernetes> kubectl get service
error: You must be logged in to the server (Unauthorized)
